version: '3'
services:
  database:
    container_name: morag_db
    image: postgres:15.2
    environment:
      - PGPASSWORD=morag
      - POSTGRES_DB=morag
      - POSTGRES_USER=morag
      - POSTGRES_PASSWORD=morag
      - POSTGRES_ROOT_PASSWORD=password
    ports:
      - '3309:3306'
      - '4444:5432'
    networks:
      db:

networks:
  web:
  db:
